codecov:
    notify:
        require_ci_to_pass: yes

comment:
    behavior: default
    layout: "header, diff"
    require_changes: no

coverage:
    precision: 2
    range: "70...100"
    round: down

    status:
        changes: no
        patch: yes
        project: yes

ignore:
    - "**/*BaseTest"
    - "**/*ClientTest"
    - "**/*IntegrationTest"
parsers:
    gcov:
        branch_detection:
            conditional: yes
            loop: yes
            method: no
            macro: no